### ISSUE TITLE
how to get detection features

### ISSUE THREAD

**Issue by a1391651300** [aimagelab/show-control-and-tell#10]
Could you please show the codes on  how can we get the detection  features? You know we can only run the test dataSet through downloading the detection feature

**Comment by marcellacornia** [comment]
Hi @a1391651300,
thanks for your interest in our work.

We extracted the detection features by using the code of the Bottom-up Top-down paper (_i.e._ https://github.com/peteanderson80/bottom-up-attention).

**Comment by a1391651300** [comment]
Tank you fo your answer very much. Does it means that I can infer new images on the detction code?
