### ISSUE TITLE
Does coco_detections.hdf5  have to be downloaded ？

### ISSUE THREAD

**Issue by SmallSmallQiu** [aimagelab/show-control-and-tell#11]
Do I need to download coco_detections.hdf5 ? If I have COCO pictures, can I generate them by myself

**Comment by marcellacornia** [comment]
Hi @SmallSmallQiu,
thanks for your interest in our work.

To generate the `coco_detections.hdf5`, we used the code of the Bottom-up Top-down paper (_i.e._ https://github.com/peteanderson80/bottom-up-attention).
