### ISSUE TITLE
Got some trouble with install speaksee

### ISSUE THREAD

**Issue by AlanHuang1998** [aimagelab/show-control-and-tell#13]
Thanks for sharing,
I got ERROR when I install the requirement torch, the situation is the same as seen in the photo.
![image](https://user-images.githubusercontent.com/36326341/67658223-eccedf00-f993-11e9-8456-01e5727ac033.png)

Is there any way to solve it?

**Comment by marcellacornia** [comment]
Hi @AlanHuang1998,
did you solve the problem?

**Comment by AlanHuang1998** [comment]
@marcellacornia 
Solved it, but got another problem, when I use "python test_region_set.py --dataset coco --exp_name ours --sample_rl_nw" to run, looks like take too long time to download something, so the server shutdown the connection, photo below.
![1572336749494](https://user-images.githubusercontent.com/36326341/67749134-78657000-fa67-11e9-8f03-55a8392b2c78.jpg)

I'm rookie in image caption, want to ask how to train the model to get sentences. Just like you demonstrated.

**Comment by marcellacornia** [comment]
The tgz file is needed to calculate the spice metric. If the download is too slow, you can comment the two lines of code that calculate the spice score.

```
val_spice, _ = Spice().compute_score(gts_t, gen_t)
print('SPICE', val_spice)
```

**Comment by AlanHuang1998** [comment]
Thanks for your help! I follow your instructions and get each score.
Want to ask how to use the model to get a full sentences, like the picture below. Thank you!
![1573650778679](https://user-images.githubusercontent.com/36326341/68766978-df377b80-065a-11ea-9d58-52e0f3d181c1.jpg)

**Comment by tejasri19** [comment]
@marcellacornia @AlanHuang1998 
When I run `python test_region_set.py --dataset coco --exp_name ours --sample_rl_nw,` i get import errors of speaksee.data. However the installation shows successful.
![Screenshot_20200428_153843](https://user-images.githubusercontent.com/22271616/80475481-90f70a00-8966-11ea-98ef-84c012641172.png)
