### ISSUE TITLE
 No such file or directory: 'java': 'java'

### ISSUE THREAD

**Issue by SmallSmallQiu** [aimagelab/show-control-and-tell#15]
When I run the test_region_sequence.py,
If you run on Linux from the command line, you won't get an error
But running on pycharm will report this error. How can I solve it
![Uploading 1573543694(1).jpg…]()

**Comment by SmallSmallQiu** [comment]
![1573543694(1)](https://user-images.githubusercontent.com/44115671/68650950-27727300-0561-11ea-827c-43785171885c.jpg)

**Comment by SmallSmallQiu** [comment]
This is because pycharm did not read the configuration file of the Linux server

**Comment by HenryJunW** [comment]
Same problem, did you find the solution?
