### ISSUE TITLE
BrokenPipeError: [Errno 32] Broken pipe

### ISSUE THREAD

**Issue by AaronXinWu** [aimagelab/show-control-and-tell#20]
python test_region_sequence.py --dataset flickr --exp_name ours --sample_rl_nw
Loading "ours" model trained with CIDEr + NW optimization.
Test: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 63/63 [02:37<00:00,  2.09s/it]
Computing sequence contrallabity results.
Blue_1 0.4043501599100964
Bleu_2 0.265110236768992
Bleu_3 0.17974917026202153
Bleu_4 0.1251760198819223
Traceback (most recent call last):
  File "test_region_sequence.py", line 175, in <module>
    val_meteor, _ = Meteor().compute_score(gts_t, gen_t)
  File "/root/anaconda3/lib/python3.7/site-packages/speaksee/evaluation/meteor/meteor.py", line 48, in compute_score
    stat = self._stat(res[i][0], gts[i])
  File "/root/anaconda3/lib/python3.7/site-packages/speaksee/evaluation/meteor/meteor.py", line 65, in _stat
    self.meteor_p.stdin.flush()
BrokenPipeError: [Errno 32] Broken pipe

**Comment by tejasri19** [comment]
> (sct) tejasrii@winet:~/show_control_tell$ python test_region_sequence.py --dataset coco --exp_name ours --sample_rl_nw  
Namespace(batch_size=16, dataset='coco', exp_name='ours', nb_workers=0, sample_rl=False, sample_rl_nw=True)
Loading "ours" model trained with CIDEr + NW optimization.
Test:   0%|                                                                                                                                                                                      | 0/224 [00:01<?, ?it/s]
Traceback (most recent call last):
  File "test_region_sequence.py", line 138, in <module>
    out, _ = model.beam_search((detections_i, ctrl_det_seqs_test_unique), eos_idxs=[text_field.vocab.stoi['<eos>'], -1], beam_size=5)
  File "/home/tejasrii/show_control_tell/models/CaptioningModel.py", line 151, in beam_search
    selected_logprob, selected_idx = torch.sort(seq_logprob.view(b_s, -1), -1, descending=True)
RuntimeError: view size is not compatible with input tensor's size and stride (at least one dimension spans across two contiguous subspaces). Use .reshape(...) instead.
(sct) tejasrii@winet:~/show_control_tell$

**Comment by tejasri19** [comment]
`(sct) tejasrii@winet:~/show_control_tell$ python test_region_sequence.py --dataset coco --exp_name ours --sample_rl_nw  
Namespace(batch_size=16, dataset='coco', exp_name='ours', nb_workers=0, sample_rl=False, sample_rl_nw=True)
Loading "ours" model trained with CIDEr + NW optimization.
Test:   0%|                                                                                                                                                                                      | 0/224 [00:01<?, ?it/s]
Traceback (most recent call last):
  File "test_region_sequence.py", line 138, in <module>
    out, _ = model.beam_search((detections_i, ctrl_det_seqs_test_unique), eos_idxs=[text_field.vocab.stoi['<eos>'], -1], beam_size=5)
  File "/home/tejasrii/show_control_tell/models/CaptioningModel.py", line 151, in beam_search
    selected_logprob, selected_idx = torch.sort(seq_logprob.view(b_s, -1), -1, descending=True)
RuntimeError: view size is not compatible with input tensor's size and stride (at least one dimension spans across two contiguous subspaces). Use .reshape(...) instead.
(sct) tejasrii@winet:~/show_control_tell$ `

**Comment by tejasri19** [comment]
@baraldilorenzo  help needed!
Runtime error occurs when I tried to run saved models to test regions in sequences.
`Traceback (most recent call last):
  File "test_region_sequence.py", line 138, in <module>
    out, _ = model.beam_search((detections_i, ctrl_det_seqs_test_unique), eos_idxs=[text_field.vocab.stoi['<eos>'], -1], beam_size=5)
  File "/home/tejasrii/show_control_tell/models/CaptioningModel.py", line 151, in beam_search
    selected_logprob, selected_idx = torch.sort(seq_logprob.view(b_s, -1), -1, descending=True)
RuntimeError: view size is not compatible with input tensor's size and stride (at least one dimension spans across two contiguous subspaces). Use .reshape(...) instead.`

**Comment by cws7777** [comment]
> @baraldilorenzo Please help
> Runtime error occurs when I tried to run saved models to test regions in sequences.
> `Traceback (most recent call last): File "test_region_sequence.py", line 138, in <module> out, _ = model.beam_search((detections_i, ctrl_det_seqs_test_unique), eos_idxs=[text_field.vocab.stoi['<eos>'], -1], beam_size=5) File "/home/tejasrii/show_control_tell/models/CaptioningModel.py", line 151, in beam_search selected_logprob, selected_idx = torch.sort(seq_logprob.view(b_s, -1), -1, descending=True) RuntimeError: view size is not compatible with input tensor's size and stride (at least one dimension spans across two contiguous subspaces). Use .reshape(...) instead.`

@baraldilorenzo Hi, I'm having same problem as you got.. 
Did you figure out the problem?

Thanks

**Comment by cws7777** [comment]
@baraldilorenzo I don't know whether you figured out already or not, but I figured out by changing view() to reshape() on line 151 in CaptioningModel.py

**Comment by tejasri19** [comment]
@AaronXinWu @baraldilorenzo I'm getting this error when i tried to run saved models to test regions in sequences. Any idea?

`(sct) tejasrii@winet:~/show_control_tell$ python test_region_set.py --dataset coco --exp_name ours --sample_rl_nw
Namespace(batch_size=16, dataset='coco', exp_name='ours', nb_workers=0, sample_rl=False, sample_rl_nw=True)
Loading "ours" model trained with CIDEr + NW optimization.
Test: 100%|███████████████████████████████████████████████████████████| 224/224 [14:14<00:00,  3.82s/it]
Computing set contrallabity results.
Traceback (most recent call last):
  File "test_region_set.py", line 216, in <module>
    gts_t = PTBTokenizer.tokenize(gts)
  File "/home/winet/anaconda3/envs/sct/lib/python3.6/site-packages/speaksee/evaluation/tokenizer.py", line 41, in tokenize
    tmp_file = tempfile.NamedTemporaryFile(delete=False, dir=path_to_jar_dirname)
  File "/home/winet/anaconda3/envs/sct/lib/python3.6/tempfile.py", line 551, in NamedTemporaryFile
    (fd, name) = _mkstemp_inner(dir, prefix, suffix, flags, output_type)
  File "/home/winet/anaconda3/envs/sct/lib/python3.6/tempfile.py", line 262, in _mkstemp_inner
    fd = _os.open(file, flags, 0o600)
PermissionError: [Errno 13] Permission denied: '/home/winet/anaconda3/envs/sct/lib/python3.6/site-packages/speaksee/evaluation/tmpi3t7_mxs'
`
