### ISSUE TITLE
new image not in coco 

### ISSUE THREAD

**Issue by YoussefSaadYoussef** [aimagelab/show-control-and-tell#22]
How to extract the features of the images not in the coco or flicker datasets to generate its captions?

**Comment by marcellacornia** [comment]
Dear @YoussefSaadYoussef,
thanks for your interest in our work.

For the moment, it is not possible to test our model on new images.

For each input image, our model takes as input a control signal in the form of a sequence or a set of image regions and predicts an output caption following the given control. In our experiments, we use the control signals coming from COCO and Flickr30k captions.
