### ISSUE TITLE
Can't find the features of test split in coco_detections.hdf5

### ISSUE THREAD

**Issue by Sisi0518** [aimagelab/show-control-and-tell#29]
Hi, 

Why I can't find the entities' features of test split image in coco_detections.hdf5?
There are 4995 images that annotated as 'test' in coco_entities_release.json, but I can't find their entities' features in coco_detections.hdf5.

Thanks!

**Comment by marcellacornia** [comment]
Hi @Sisi0518, 
the COCO detection file contains all train, validation, and test images of our COCO Entities dataset. 

Recall that the images from the test set are part of the validation split of the COCO 2014 version, so their names starts with `COCO_val2014`.
