### ISSUE TITLE
The way to extract noun chunks

### ISSUE THREAD

**Issue by zhengyi123456** [aimagelab/show-control-and-tell#3]
Hi, could you provide the code to extract noun chunks or details about how you do that?

**Comment by zhengyi123456** [comment]
For people who are also have this question. SpaCy toolkit provides API to extract noun chunks directly. By the way, I also sent a e-mail last to the author, sorry for bothering, this is my carelessness.

**Comment by marcellacornia** [comment]
Hi @zhengyi123456, 
thanks again for your interest in our work!

As already mentioned by email, we actually used the spaCy NLP toolkit to automatically extract noun chunks from the COCO captions.
