### ISSUE TITLE
Why are there multiple detection regions for the same instance

### ISSUE THREAD

**Issue by Sisi0518** [aimagelab/show-control-and-tell#30]
Hi

Why are there multiple detection regions for the same instance in coco_entities_release.json,  such as: 
u'women': [[17, 
      [211.71670532226562,
      21.305891036987305,
      428.42095947265625,
      386.89093017578125]],
    [23,
     [98.44943237304688,
      94.96699523925781,
      302.0435485839844,
      318.7557678222656]],
    [38,
     [228.9897918701172,
      72.67094421386719,
      458.8382263183594,
      418.9734191894531]]]}

And is there any difference between them?

Thanks!

**Comment by marcellacornia** [comment]
Hi @Sisi0518,
in our COCO Entities dataset we use the predicted regions coming from Faster R-CNN finetuned on the Visual Genome dataset. The predicted bounding boxes can be more than one for each detected object thus having multiple detections for each entity. 
In our model, we use all predicted detections for each considered region.
