### ISSUE TITLE
object_class_list.txt

### ISSUE THREAD

**Issue by oashdouahsd** [aimagelab/show-control-and-tell#31]

**Comment by wangyuanshun** [comment]
excuse me,have you got the idea? thanks lot

**Comment by marcellacornia** [comment]
Hi @miaoyi322  and @wangyuanshun,

For the moment, it is not possible to test our model on new images outside COCO and Flickr30k datasets.

Recall that, for each input image, our model takes as input a control signal in the form of a sequence or a set of image regions and predicts an output caption following the given control. In our experiments, we use the control signals coming from COCO and Flickr30k captions.

**Comment by miaoyi322** [comment]
Thanks for your reply. I have got this. 
However, how to get the results in the figure 4/5/6/8/9? These images are COCO/Flickr30k images.
Could you share a demo? I'll appreciate that.

**Comment by miaoyi322** [comment]
figure 4/5/6/8/9  in your paper:  Show, Control and Tell: A Framework for Generating Controllable and Grounded Captions

**Comment by wangyuanshun** [comment]
You are misunderstood, I am not the author of the paper, I am also the person who studies this paper, I also want to know how to generate pictures 4/5/8/9/10, the paper does not seem to involve how to generate, can you give me some guidance ?thanks lot.




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "miaoyi322"<notifications@github.com&gt;; 
发送时间: 2020年7月23日(星期四) 下午5:53
收件人: "aimagelab/show-control-and-tell"<show-control-and-tell@noreply.github.com&gt;; 
抄送: "转让半包辣条"<1714113169@qq.com&gt;; "Mention"<mention@noreply.github.com&gt;; 
主题: Re: [aimagelab/show-control-and-tell] How to generate a caption for picture? (#31)





 
Thanks for your reply. I have got this.
 However, how to get the results in the figure 4/5/6/8/9? These images are COCO/Flickr30k images.
 Could you share a demo? I'll appreciate that.
