### ISSUE TITLE
When will you provide the  training code and put it on GitHub?

### ISSUE THREAD

**Issue by whut2962575697** [aimagelab/show-control-and-tell#6]
Thanks for your great work!I found that you provided the verification code of the controllable captioning model , but there is no training  code. I want to know if you are convenient to provide the code of training part or put it on GitHub.

**Comment by marcellacornia** [comment]
Hi @whut2962575697, 
thank you for your interest in our work! 

The training code is now available. I hope it will be useful.

**Comment by whut2962575697** [comment]
Thanks for your reply！We are very grateful that you can provide us with the training code which will be very useful to us.
Thank you and best regards.
Yours sincerely,
Xin He


2962575697@whut.edu.cn
 
From: Marcella Cornia
Date: 2019-07-23 00:33
To: aimagelab/show-control-and-tell
CC: Clark He; Mention
Subject: Re: [aimagelab/show-control-and-tell] When will you provide the training code and put it on GitHub? (#6)
Hi @whut2962575697,
thank you for your interest in our work!
The training code is now available. I hope it will be useful.
