### ISSUE TITLE
Download speed is so slow!

### ISSUE THREAD

**Issue by songsonggithub** [aimagelab/show-control-and-tell#8]
Hi! 
In the process of downloading coco and Flickr30k, the speed is so slow and it break off sometimes! Do you have other way to let me get it? I really want to try the code.

**Comment by baraldilorenzo** [comment]
There are Google Drive links in the readme as an alternative. Let me know if you still have issues.

Best,
Lorenzo.

**Comment by songsonggithub** [comment]
Thanks! The speed of download is several times faster.
