### ISSUE TITLE
Sorry, how can I get the flickr30k Entities dataset?

### ISSUE THREAD

**Issue by Wangzhen-kris** [aimagelab/show-control-and-tell#9]
Thanks for your great work! I have read in README about:
**If you want to use only the annotations of our COCO Entities dataset, you can download the annotation file coco_entities_release.json (~403 MB).**
And I think it's so interesting! But I can't find the way to generate the flickr30k entities dataset, can you help me?

**Comment by marcellacornia** [comment]
Hi @JonasWangCN,
thanks for your interest in our work.

The Flickr30k Entities dataset was not proposed in our work. You can download the annotations in the original dataset page: http://bryanplummer.com/Flickr30kEntities/.
